POST  http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: bearer 

    {
        "title": "Kommenttien testaus backendissä2",
        "author": "Minä itse tietenkin",
        "url": "https://fullstackopen.com/osa7/tehtavia_blogilistan_laajennus2",
        "likes": 4,
        "comments": ["Tää vois vaikka toimia", "asdasdadada"]
    }
